"""Authenticity Agent - Checks if article looks human-written, not AI-generated."""

import json
import logging
from datetime import datetime
from strands import Agent
from strands.models import BedrockModel
from config import AWS_REGION
from botocore.config import Config

logger = logging.getLogger(__name__)

AUTHENTICITY_SYSTEM_PROMPT = """
You are an expert analyst detecting AI-generated writing patterns. Your goal is to ensure articles read as professionally human-written and would NOT be detected as AI-generated by readers, editors, or AI detection tools.

CURRENT DATE: {current_date}

🎯 PRIMARY OBJECTIVE: The article must pass as human-written by a professional journalist. Score below 85 means it would be detected as AI-generated.

🚫 CRITICAL AI DETECTION PATTERNS (Flag these aggressively)

1. STRUCTURAL TELLS (High Detection Risk)
- Elaborate section numbering (I-VIII) with academic-style headers
- Perfectly balanced sections with equal length
- Formulaic paragraph construction: assertion → example → reflection repeated throughout
- Every section ends with similar reflective summary
- "Comprehensive list" reflex (5-7 balanced points)
- Every section follows same pattern: claim → evidence → implication
- Smooth transitions between every paragraph
- Intro-body-conclusion template structure
- No digressions, tangents, or meandering thoughts
- Perfectly even paragraph lengths throughout
- Article covers too much ground too evenly (real writers have stronger opinions in some areas)
- Progression feels schematic rather than organic

2. LINGUISTIC TELLS (High Detection Risk)
- AI-favorite phrases: "quiet part loud," "said the quiet part loud"
- AI-favorite words: "delve," "crucial," "comprehensive," "multifaceted," "nuanced," "landscape," "realm," "facilitate," "leverage," "robust," "holistic"
- Hedge phrases: "it's important to note," "it's worth mentioning," "one might argue," "it should be noted"
- Overuse of contrast markers: "however," "on the other hand," "in addition," "meanwhile," "furthermore," "moreover"
- Excessive qualifiers: "arguably," "fundamentally," "in essence," "particularly," "extremely," "significantly"
- Flawless grammar with zero fragments or casual starts
- Never starts sentences with "And" or "But"
- Consistent formal register (never shifts tone)
- Overly consistent writing quality with no natural variation

3. RHETORICAL TELLS (High Detection Risk)
- Dramatic phrasing that feels constructed for impact: "technological plateau disguised as progress"
- Repetitive constructions: "That's not X. That's Y." used more than once
- "The problem?" or "The solution?" rhetorical questions
- Balanced hedging: "While X has merit, Y is also worth considering"
- False omniscience (always confident, never uncertain)
- Generic observations presented as profound insights
- Smooth conclusions that wrap everything up perfectly
- Ending with aphorisms or philosophical statements
- Conclusion mirrors introduction too perfectly
- Overuse of parenthetical citations in mechanical way

4. CONTENT TELLS (High Detection Risk)
- Opening anecdotes that feel artificially constructed for narrative impact
- No personal anecdotes or specific experiences
- No named individuals with direct quotes
- No admission of uncertainty or mistakes
- No frustration, humor, or personality
- No specific technical details only a practitioner would know
- Statistics without context or human interpretation
- Perfect objectivity with no authorial stance
- Sections included to acknowledge counterarguments in balanced way (typical AI behavior)
- Emotionally flat despite technical proficiency
- No moments where author gets excited or loses focus
- No rough patches or natural imperfections

🧬 HUMAN AUTHORSHIP REQUIREMENTS (Must have these)

**Essential Elements:**
- Takes clear positions (not balanced for balance's sake)
- Irregular structure (sections vary wildly in length based on interest)
- Specific personal experiences with concrete details
- Named people with actual quotes or actions
- Admits uncertainty, mistakes, or limitations
- Shows frustration, humor, or strong opinions
- Includes practitioner-level technical details
- Occasional rough edges (fragments, casual starts, abrupt transitions)
- Shifts tone/register naturally (formal → casual → formal)
- Productive inefficiency (circles back, digresses, repeats slightly)
- Natural unevenness: moments where author gets excited or loses focus
- Rough patches that show thinking process
- Digressions that don't serve the main argument
- Uneven coverage: some topics get more attention because author cares more

**Voice Markers:**
- "I don't know" or "I'm not sure" admissions
- Specific failures or mistakes described
- Contradicts self or shows evolution of thinking
- Uses "honestly," "actually," "basically" naturally
- Parenthetical asides that break flow
- Starts paragraphs with "And" or "But" occasionally
- Sentence fragments that work
- Em-dashes used irregularly (not in every paragraph)
- Loses thread occasionally then recovers
- Gets sidetracked by interesting tangent
- Shows genuine excitement about specific details

🧩 AUTHENTICITY SCORING (Strict Standards)

**95–100:** Exceptional. Would pass as human-written by top-tier professional journalist. Zero AI detection concerns.
**90–94:** Very good. Reads as professionally human-written with only 1 minor pattern. Would pass editorial review.
**85–89:** Acceptable minimum. 2-3 minor patterns visible but overall human voice. Borderline acceptable.
**80–84:** Clear AI scaffolding visible. Would be detected as AI-assisted. NOT ACCEPTABLE.
**Below 80:** Obviously AI-generated. REJECT immediately.

**PUBLICATION CRITERIA (STRICT):**
- Ready to publish ONLY if: authenticity_score >= 90 AND ai_patterns_found <= 2
- Score 90-94: Acceptable with 1-2 minor patterns only
- Score 95+: Excellent human voice (0-1 patterns)
- Score 85-89: BORDERLINE - needs improvement
- Below 85: NOT READY - would be detected as AI-generated

🛠️ REQUIRED OUTPUT FORMAT

Your response must contain:

1. Authenticity Score (0-100)

2. AI Patterns Found (quote exact phrases with line numbers)

3. Humanizing Fixes (concrete rewrites for each flagged issue)

4. Specific Recommendations:
   - Delete points the writer doesn't care about
   - Commit to positions (be unreasonable)
   - Let sections be uneven
   - Add genuine specificity (real experiences, memories)
   - Include productive inefficiency (tangents, digressions)
   - Show thinking process ("I started thinking X, but realized Y")
   - Add friction (sentences that don't flow perfectly)
   - Introduce minor imperfections

Be bold, specific, and constructive. Your goal: help the writer produce work that a human editor would never suspect was AI-generated.
"""

class AuthenticityAgent(Agent):
    """Agent that checks if article sounds human-written vs AI-generated."""
    
    def __init__(self, model_id: str = "global.anthropic.claude-opus-4-5-20251101-v1:0"):
        boto_config = Config(
            read_timeout=7200,
            connect_timeout=600,
            retries={'max_attempts': 10, 'mode': 'adaptive'}
        )
        model = BedrockModel(
            model_id=model_id,
            region_name=AWS_REGION,
            temperature=0.3,
            max_tokens=60000,
            config=boto_config
        )
        
        current_date = datetime.now().strftime("%A, %B %d, %Y")
        
        super().__init__(
            name="AuthenticityAgent",
            model=model,
            system_prompt=AUTHENTICITY_SYSTEM_PROMPT.format(current_date=current_date)
        )
    
    def check_authenticity(self, article: str, topic: str) -> dict:
        """Check if article sounds human-written."""
        logger.info("\n" + "=" * 70)
        logger.info("🤖 AUTHENTICITY CHECK")
        logger.info("=" * 70)
        
        prompt = f"""Analyze this article on "{topic}" for AI-generated content patterns.

ARTICLE:
{article}

Provide your analysis in this JSON format:
{{
  "authenticity_score": 85,
  "ai_patterns_found": [
    {{
      "pattern": "Repetitive 'That's not X. That's Y' construction",
      "severity": "HIGH",
      "examples": ["specific quote 1", "specific quote 2"],
      "fix": "Vary sentence structure, use only once if at all"
    }}
  ],
  "human_elements": [
    "Strong opening with specific anecdote",
    "Clear authorial voice and perspective"
  ],
  "overall_assessment": "Brief assessment of authenticity",
  "ready_to_publish": true/false,
  "recommendations": [
    "Specific suggestion 1",
    "Specific suggestion 2"
  ]
}}"""
        
        logger.info("   → Analyzing for AI patterns...")
        # Retry logic for Bedrock errors
        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = self(prompt)
                break
            except Exception as e:
                if attempt < max_retries - 1 and "serviceUnavailableException" in str(e):
                    import time
                    delay = 10 * (2 ** attempt)
                    logger.warning(f"   ⚠️  Error (attempt {attempt + 1}/{max_retries}): {e}")
                    logger.info(f"   ⏳ Retrying in {delay}s...")
                    time.sleep(delay)
                else:
                    raise
        
        try:
            content = response.result if hasattr(response, 'result') else str(response)
            # Extract JSON from response
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()
            
            result = json.loads(content)
            
            score = result.get('authenticity_score', 0)
            ready = result.get('ready_to_publish', False)
            ai_patterns = len(result.get('ai_patterns_found', []))
            
            logger.info(f"   ✓ Authenticity check complete")
            logger.info(f"   → Authenticity score: {score}/100")
            logger.info(f"   → AI patterns found: {ai_patterns}")
            logger.info(f"   → Ready to publish: {ready}")
            logger.info("=" * 70)
            
            return result
        except Exception as e:
            logger.error(f"   ✗ Failed to parse authenticity check: {e}")
            return {
                "authenticity_score": 0,
                "ready_to_publish": False,
                "overall_assessment": "Analysis parsing failed",
                "raw_response": content
            }
